name: Scrape Codeforces Solutions

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install requests beautifulsoup4
          
      - name: Run the scraper script
        env:
          CF_HANDLE: ${{ secrets.CF_HANDLE }}
          CF_CLEARANCE: ${{ secrets.CF_CLEARANCE }}
          SESSION_ID: ${{ secrets.SESSION_ID }}
          USER_AGENT: ${{ secrets.USER_AGENT }} # Add this line
        run: python scraper.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions-bot@github.com"
          git add -A
          if git diff --staged --quiet; then
            echo "No new solutions to commit."
          else
            git commit -m "feat: ✨ Add new scraped Codeforces solutions"
            git push
          fi
